neurobagel/api

.github/workflows/test.yaml
The main change is the addition of .github/workflows directory and test.yaml file used to set up test workflow
Closes #19
=> Set up test workflow

tests/test_query.py
`test_get_input` now tests all accepted values for the "sex" parameter.
Closes #22 .
=> Parameterization of test for valid sex query

.github/workflows/test.yaml, requirements.txt
Updated workflow .yaml so that an LCOV report is now generated during testing, and added [Coveralls](https://github.com/marketplace/actions/coveralls-github-action) Github action for coverage data reporting.
Closes #38
=> Set up code coverage reporting

.github/workflows/test.yaml, README.md, app/api/models.py
=> Updated README.md and Modified Workflow Trigger Events

app/api/crud.py, app/api/models.py, app/api/routers/query.py, app/api/utility.py, tests/test_query.py
=> Implemented minimum number of imaging sessions query parameter

app/api/utility.py
=> Added optional type annotation to arguments of create_query function in utility.py module

.github/workflows/test.yaml
`workflow_dispatch` trigger event replaced with `push`.
Closes #58
=> Update test workflow to run on push

Dockerfile, README.md
=> Add Dockerfile and instructions for deploying API using official Docker image

.pre-commit-config.yaml
=> bump isort to v5.12.0

app/main.py
=> Added cors middleware to the api

app/api/models.py
=> Turned the regex in QueryModel class to a reusable constant

README.md, app/api/utility.py, docker-compose.yml
- Default Stardog image tag also updated to reflect our current license.
Closes #91
=> Make graph database name configurable as an environment variable

app/api/utility.py
=> Refactor generation of query template

.codespellrc, .github/workflows/codespell.yml, .pre-commit-config.yaml
=> codespell: pre-commit, config, workflow

README.md, app/api/crud.py, app/api/utility.py, app/main.py, docker-compose.yml, tests/test_query.py
Closes #114, closes #115
- Current environment variables (variables that can currently be configured in a user/sysadmin shell) have been renamed to have an `NB` prefix to minimize clashes with other shell vars
- Internal storage of environment variables has been changed to use `namedtuples` so that variable names can be changed/accessed more programmatically, and is handled by utility.py to keep things in one place; tests updated
- Table added to README to list and describe all environment variables in one place
=> [FIX] Update names + storage of env variables to avoid conflicts + for ease of access

.template-env
- Mislabeled environment variable fixed
For bug fixes:
=> [FIX] Fix typo in .template-env

docker-compose.yml, docs/api_environment_variables.tsv
=> [FIX] Removed the nested variable for `API_QUERY_URL` env var

.pre-commit-config.yaml, docs/api_environment_variables.tsv
=> [MNT] Added `docker-pre-commit` pre-commit hook

app/api/utility.py
=> [MNT] Add NCIT namespace and update healthy control term

app/api/crud.py, app/api/models.py, tests/conftest.py
Closes #171
Closes #192 
- Session paths now provided as dictionaries
- New boolean key `records_protected` added to indicate whether API is set up to return aggregate results
For bug fixes:
=> [ENH] Update aggregate response body

add_data_to_graph.sh
=> [ENH] Update `add_data_to_graph.sh` to also upload TTL files

app/api/crud.py, tests/conftest.py, tests/test_query.py
=> [FIX] Filtered out `null` imaging modalities

.github/workflows/build_docker.yaml
- Closes #239 
- Closes #240 
For bug fixes:
=> [CI] Renamed `ci` workflow to `build_docker` and image tag from `latest` to `nightly`

README.md, app/api/utility.py, docs/default_neurobagel_query.rq
- Closes #276 
- Default indentation of f-strings in query template modified using `textwrap` so that output of `create_query()` is always correctly indented (without disturbing code tidiness by outdenting everything)
For bug fixes:
=> [DOC] Add sample default SPARQL query to repo

requirements.txt
- Closes #292 
- Closes #293 
- Closes #294 
For bug fixes:
=> Bumped fastapi, starlette, and typing_extensions

app/api/crud.py
- Closes #304 
- Default httpx request timeout disabled
For bug fixes:
=> [FIX] Disable timeout for request to graph

.github/workflows/build_docker_on_release.yml
- Variables defined for GH Actions should be accessed through the `vars` context, not the `env` context !
- This PR will be used to trigger a release
For bug fixes:
=> [CI] Fix reference for `DOCKERHUB_REPO` in build_docker_on_release.yml

app/api/utility.py, docs/default_neurobagel_query.rq
Refactored `query_string` in `utility` module
For bug fixes:
=> [MNT] Updated `default_neurobagel_query`

.github/pull_request_template.md, docs/default_neurobagel_query.rq
- Since it's easy to forget to update our standalone [file](https://github.com/neurobagel/api/blob/main/docs/default_neurobagel_query.rq) documenting the default Neurobagel SPARQL query when we change the query template as part of a PR, this PR adds a checkbox to the PR template to check that this has been done
For bug fixes:
=> [MNT] Update default Neurobagel SPARQL query file and turn into PR checkbox
