neurobagel/api

app/api/crud.py, app/api/models.py, app/api/routers/query.py, app/api/utility.py, requirements.txt, tests/test_query.py
The main changes are:
- Modified SPARQL query to not return any subject-level phenotypic info
- Created + implemented data model for aggregate responses (dataset, dataset name, number of matching subjects)
- Updated tests to use aggregate responses
Closes #50
Closes #49 
Closes #52
=> Modify query path to return only aggregate subject info

app/api/utility.py
`DOG_ROOT` in utility.py will now use `DOG_ROOT` in the user's environment if it's set, or otherwise have a default value of "206.12.99.17".
Closes #68
=> Change variable storing graph DB IP address to an environment variable

app/api/crud.py, app/api/utility.py, app/main.py, requirements.txt
Main changes:
- Added `bg:isSubjectGroup` to `query_template`, Closes #44 
- Wrapped age, sex, diagnosis, subject group, and assessment with sparql optional pattern, Closes #72
=> Modified `query_template` in utility.py

Dockerfile, README.md, app/api/crud.py, app/api/utility.py, app/main.py, docker-compose.yml, tests/test_query.py
Other changes:
The `USER` variable has been renamed everywhere to `USERNAME` to try to avoid name conflicts on Linux systems where `USER` is automatically set in the shell. This is more of a precaution; a note has also been added in the README which recommends that the user verifies that the values of the credentials pair is correct.
Closes #86 
Closes #78
=> Add docker-compose specification and instructions

README.md, app/api/models.py, app/api/utility.py, tests/test_query.py
Notes:
- Fixed options for sex (based on the test graph) were previously string literals (`"male"`, `"female"`, `"other"`) and not URIs. In this PR the options have been changed to a single controlled term regex field
- Minor typos in README also fixed.
Closes #94
=> Update controlled terms to conform to new naming conventions

app/api/crud.py, app/api/models.py, app/api/utility.py, tests/test_query.py
Closes #112 
- in models.py, add to CohortQueryResponse data model:
-  `dataset_portal_uri`
- `dataset_file_path`
- update query string to return from graph, in addition to existing variables:
- dataset PortalURI (using `hasPortalURI`)
- dataset FilePath (using `hasFilePath`)
- SessionID (using `hasLabel`)
- Renamed `file_path` to `session_file_path`
- remove `dataset` (i.e., unique dataset identifier, `https://iri.nidash...`) and `subject` IRIs from returned variables in query string
- in crud.py, when constructing `subject_data` dataframe from graph-returned data:
- remove `dataset_name` for each subject entry
- group acquisitions by subject and session such that each row is a subject-session, and `diagnosis` and `modality` become lists
- Updated …
=> [ENH] Updated API to return new subject level results 

app/api/crud.py, app/api/models.py, app/api/utility.py, tests/test_query.py
Closes #129 
Closes #130 
See also https://github.com/neurobagel/project/issues/141
- removed `dataset_file_path` from results model & query template
- removed `dataset_file_path` from crud.py results processing
- added unique dataset identifier (directly obtained from graph) back into results model
- updated test examples
- made `dataset_portal_uri` optional in `CohortQueryResponse` and query template
- modified `IS_CONTROL_TERM` to match the cli generated jsonld
For bug fixes:
=> [MAINT] Openneuro updates

app/api/crud.py
=> [FIX] Return list instead of only first term for subject-level assessment

.github/workflows/cff_validation.yml, CITATION.cff
Relates to #76 
- add a citation file and a workflow to validate it
For bug fixes:
=> [INFRA] add citation cff and validation workflow

docker-compose.yml
Closes #163
- remove the dash
Possibly still to be done:
- confirm this is actually a yaml-list (i.e. `-` dash) issue
- can we test this so it doesn't happen again?
For bug fixes:
=> [FIX] Remove yaml list key for API_QUERY_URL

.template-env, README.md, docs/api_environment_variables.tsv
Closes #153
- Moved environment variables table into separate TSV file to link to from the official docs using [mkdocs-yamp](https://github.com/boozallen/mkdocs-yamp-plugin)
- Simplified README to link to docs section on environment variables (which includes a copy of info about configuring origins, etc.) to keep README focused on installation and launch steps
- Moved info for deploying a query tool as part of the Compose network to the docker compose section
For bug fixes:
=> [REF] Remove environment variable table from README

vocab/nb_vocab.ttl
Closes #182 
Reference for our currently used classes: https://github.com/neurobagel/bagel-cli/blob/main/bagel/models.py
See also https://github.com/neurobagel/api/issues/185 for suggested modification of `add_data_to_graph.sh` to support uploading vocab files to the graph
For bug fixes:
=> [ENH] Add Neurobagel vocab graph file

app/api/crud.py, app/api/routers/attributes.py, app/api/routers/query.py, app/api/utility.py, app/main.py, tests/conftest.py, tests/test_query.py
Closes #176 
Closes #186 
- New router created for paths under the `/attributes` prefix
- Existing endpoint for terms discovery: also moved under this prefix, i.e. `/attributes/{data_element_URI}`
- New endpoint created that returns all subclasses of `nb:ControlledTerm`
- Query string for existing terms discovery endpoint updated to return URIs for only instances of controlled term subclasses
- Helper function added to abbreviate namespaces in term URLs from the graph (e.g., `"http://neurobagel.org/vocab/Diagnosis"` -> `"nb:Diagnosis"`)
For bug fixes:
=> [ENH] Add endpoint returning queryable attributes + refine existing endpoint for attribute instances

docs/api_environment_variables.tsv
=> [DOC] Generalized environment variables' table

app/api/crud.py, app/api/models.py, app/api/utility.py, tests/conftest.py
Closes #210 
- Updated `create_query` function to not query `session_file_path`
For bug fixes:
=> [MNT] Removed `session_file_path` from aggregate results

README.md
Related to https://github.com/neurobagel/planning/issues/41
-
-
For bug fixes:
=> [DOC] Add link to official docs

add_data_to_graph.sh
- Closes #213
- replace the `--no-progress-meter` argument with `-s -S` which has the same effect but works on curl < 7.67.0
For bug fixes:
=> [FIX] Remove --no-progress-meter

app/api/crud.py, app/api/utility.py
- Closes #225
- Closes #134
- Closes https://github.com/neurobagel/planning/issues/79
- make session-related attributes optional for subjects in the SPARQL query template (so that it matches subjects who have phenotypic info but no [imaging] sessions**, since currently sessions aren't created for phenotypic-only data)
- since subjects with only phenotypic data don't have a `session_id` (but the `subject_data` field in the response should have a separate entry per instance of subject data), update the pandas grouper used when processing the graph response to recognize `null` session ID when grouping the data by subject + session
- otherwise, the `"subject_data"` field for these datasets will be an empty list `[]`
- for subject session-level attribute …
=> [FIX] Make session optional in SPARQL query template

.pre-commit-config.yaml, app/api/crud.py, app/api/models.py, app/api/routers/attributes.py, app/api/utility.py, app/main.py, tests/test_app_events.py, tests/test_attributes.py, vocab/backup_external/snomedct_disorder.json
- Closes #211 
- Added JSON dump of SNOMED CT disorder terms
- On startup, app will now read in the file of SNOMED diagnosis terms and store a lookup file where entries are in the format `<id>:<name>`
- Implemented logic for `/attributes/nb:Diagnosis/vocab` which loads + processes the lookup file contents into a `VocabLabelsResponse` object
- Added graceful exception handling for network errors encountered when requesting external vocabs on startup (cogatlas)
For bug fixes:
=> [ENH] Add support for endpoint that will return `nb:Diagnosis` options from SNOMED

Dockerfile
- Closes #230
- Fixes a bug where the SNOMED terms JSON dump cannot be found by the app on startup, because the `vocab/` directory doesn't exist in the container.
For bug fixes:
=> [FIX] Copy `vocab/` directory into container filesystem in Dockerfile

.template-env, README.md, docker-compose.yml
- Closes #226
- updated the template
- rewrote README section to point to docs
- removed query tool from docker compose stack
For bug fixes:
=> [FIX] Remove query tool config

.pre-commit-config.yaml
- Closes #254 
Note: different Python repos require different pre-commit hooks, so `autofix: False` has to be set manually in each `.pre-commit-config.yaml`
For bug fixes:
=> [CI] Update pre-commit CI config

requirements.txt
- Closes #258 
**For reviewer: thoughts on whether this should be a `skip-release` PR (won't end up in changelog) or a `pr-dependencies` (will end up in changelog)?**
For bug fixes:
=> [FIX] Update pre-commit to work with latest hooks

tests/conftest.py, tests/test_query.py
- Closes #126
- Closes #266 
- Basic test added for structure of cohort query response when `RETURN_AGG=true`
- Turned mocked get function used across query tests into a few different fixtures, with variations based on the type of value/object to be returned by the mocked function
- Specific return objects for the mocked function specified in test definitions via [indirect parametrization](https://docs.pytest.org/en/latest/example/parametrize.html#indirect-parametrization)
- `mock_successful_get` (which depends on another fixture for the return object) kept a separate function to avoid overly complicated parametrization when writing tests (i.e., you cannot easily pass one fixture as a parameter to another fixture)
For bug fixes:
=> [TST] Refactor tests

README.md
- Closes #224 
- Added warning about quoting in `.env` file for Docker commands
For bug fixes:
=> [DOC] Added warning about quoting in `.env` file for Docker commands

app/main.py, tests/test_attributes.py
- Closes #199 
- Created root endpoint with welcome message and API docs link
For bug fixes:
=> [ENH] Added root endpoint with welcome message and API docs link

app/api/utility.py, tests/test_security.py, tests/test_utility.py
- Closes #324
- Use the `BOUND` function in subquery for matching phenotypic sessions to exclude any results where a variable being filtered for does not have a value ("unbound" results - these are included by default, leading to inaccurate counts of matches)
- e.g., because all phenotypic attributes are optional, when we query for healthy controls, the default matching behaviour _includes_ any sessions that do not have the `isSubjectGroup` edge - which would be any session that has diagnosis info, since these two properties are mutually exclusive
- Make having a phenotypic session non-optional in query (since subjects should not end up in the graph if they don't have any phenotypic info)
- Minor refactoring of query template for efficiency
This PR …
=> [FIX] Exclude sessions missing a queried property from matches

Dockerfile, README.md, app/api/routers/query.py, app/main.py, tests/conftest.py, tests/test_app_events.py, tests/test_attributes.py, tests/test_query.py, tests/test_routing.py, tests/test_security.py
- Closes #327 
- API will no longer redirect requests with or without a trailing slash to the version defined in the route decorator
- `/query` route no longer expects a slash at the end (or before query params)
- Minor fix of a leftover test context issue: authentication is now explicitly enabled for tests of request authorization headers
- uvicorn command in Dockerfile updated to trust `X-Forwarded...` proxy headers from all remote IPs, to ensure we don't lose `https` from a request once behind a proxy (this should happen less with the redirects now disabled, but this change should nonetheless act as a safeguard against different proxy server setups)
For bug fixes:
=> [FIX] Disable redirect slashes globally and remove trailing `/` from `/query`

app/api/utility.py, docs/default_neurobagel_query.rq
- Closes #331
- This PR reverts a change to the query template introduced as part of https://github.com/neurobagel/api/pull/326
- Use left join approach for imaging session subquery to ensure that subjects without an imaging session are still included in the results (with a count of 0 imaging sessions)
- otherwise, due to the aggregation used in the subquery (`GROUP BY ?subject`), when the results are joined back to the main query, subjects without imaging sessions may be excluded b/c there are no rows for them in the subquery results
- Note that this is not needed for the phenotypic session subquery, because all subjects must have >=1 phenotypic session
- Update serialization of default query (note that this also includes changes from …
=> [FIX] Ensure subjects without imaging sessions are considered in main query

app/api/crud.py, app/api/models.py, app/api/routers/query.py, app/api/utility.py, docs/default_neurobagel_query.rq, tests/conftest.py, tests/test_query.py
=> [ENH] Implemented `pipeline_version` and `pipeline_name` query fields

app/api/crud.py, app/api/utility.py, tests/conftest.py
- Closes #348 
- added `pipeline_name` and `pipeline_version` to list of variables returned in the aggregate graph response
- updated API-side graph response handling to return pipeline info even in aggregate mode
- minor conditional rewriting for clearer logic
Note: In this case, some tests started failing after the graph response handling logic was updated, since the mocked aggregate response from the graph used in those tests no longer matched the expected format (good). However, we are not yet to write a test that would fail under the original bug conditions (bad), since this would require a graph with data to test against. See https://github.com/neurobagel/api/issues/283
For bug fixes:
=> [FIX] Ensure pipeline variables are returned from the graph in an aggregate query

app/api/models.py, app/api/utility.py, tests/test_query.py
- Closes #332 
- `is_control` query param now accepts `str`, with allowed values being either `"true"` (case-insensitive) or `None` via custom validation
- `str` used b/c using `Literal` to enforce allowed values of `True` or `None` doesn't play well in a query parameter (see comment in code)
- `"true"` values transformed to boolean internally
- SPARQL query now only adds filter if `is_control=True` in query
Note: the default SPARQL query file hasn't changed in this case b/c it assumes no filters are applied
For bug fixes:
=> [FIX] Allow only `"true"` or `None` for `is_control` query parameter

app/api/crud.py, tests/conftest.py, tests/test_query.py
- Fixes #368
- Comments added to clarify steps in graph response reshaping
- Add mocked non-aggregated graph response where no subjects have pipeline info
- Add test of API response for this query result case
- Handle `NaNs` for `pipeline_name` during graph response reshaping, to account for cases where there are no completed pipelines among matching sessions
For bug fixes:
=> [FIX] Ensure non-agg API doesn't error out when all matches lack pipeline data

.github/workflows/test.yaml, README.md, app/api/utility.py, docs/default_neurobagel_query.rq, tests/test_query.py
- Fixes #374 
- Closes #361 
- Update query template to exclude instances of `Session` when matching sessions (returned by default due to RDF inferencing based on class relationships)
- Run integration tests using a test graph as part of CI
For bug fixes:
=> [FIX] Filter for only `ImagingSession`s or `PhenotypicSession`s in SPARQL query
